/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodiconIcon: typeof import('./components/common/CodiconIcon.vue')['default']
    CommandsView: typeof import('./components/sections/CommandsView.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    ContentArea: typeof import('./components/layout/ContentArea.vue')['default']
    DashboardView: typeof import('./components/sections/DashboardView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    GitShareView: typeof import('./components/sections/GitShareView.vue')['default']
    LauncherView: typeof import('./components/sections/LauncherView.vue')['default']
    LogDetailDialog: typeof import('./components/sections/proxy/LogDetailDialog.vue')['default']
    LogViewer: typeof import('./components/sections/proxy/LogViewer.vue')['default']
    ModelProxyView: typeof import('./components/sections/ModelProxyView.vue')['default']
    NavRail: typeof import('./components/layout/NavRail.vue')['default']
    OverlayPanel: typeof import('./components/common/OverlayPanel.vue')['default']
    ProxyStatCard: typeof import('./components/sections/proxy/ProxyStatCard.vue')['default']
    SectionToolbar: typeof import('./components/common/SectionToolbar.vue')['default']
    SettingsView: typeof import('./components/sections/SettingsView.vue')['default']
    SkillsView: typeof import('./components/sections/SkillsView.vue')['default']
    TagChips: typeof import('./components/common/TagChips.vue')['default']
    TreeNodeItem: typeof import('./components/common/TreeNodeItem.vue')['default']
    TreeView: typeof import('./components/common/TreeView.vue')['default']
  }
}
